version: "3.9"

services:
  app:
    build:
      context: ./src
      target: production
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
      - /src/node_modules
    env_file:
      - ./src/.env
    networks:
      - postgres_bridge
      - neo4j_bridge
      - redis_bridge
    depends_on:
      - postgres
      - neo4j
      - redis
    profiles:
      - prod

  app-dev:
    build:
      context: ./src
      target: development
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./src:/src
      - /src/node_modules
    env_file:
      - ./src/.env
      - ./src/dbs/redis/.env
    networks:
      - postgres_bridge
      - redis_bridge
    depends_on:
      - postgres
    profiles:
      - dev

  postgres:
    image: postgres
    env_file:
      - ./src/dbs/postgres/.env
    volumes:
      - ./src/dbs/postgres/schema:/docker-entrypoint-initdb.d/
    networks:
      - postgres_bridge
    profiles:
      - prod
      - dev

  neo4j:
    image: neo4j
    env_file:
      - ./src/dbs/neo4j/.env
    networks:
      - neo4j_bridge
    profiles:
      - prod
      - dev

  redis:
    build:
      context: ./src/dbs/redis
      dockerfile: Dockerfile
    env_file:
      - ./src/dbs/redis/.env
    volumes:
      - ./src/dbs/redis/log:/var/db/redis/log
    networks:
      - redis_bridge
    profiles:
      - prod
      - dev

networks:
  postgres_bridge:
    driver: bridge
  neo4j_bridge:
    driver: bridge
  redis_bridge:
    driver: bridge
