name: NodeJS Automated Tests

on:
  pull_request:
    branches:
      - '*'
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
    
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
